[2023-12-30T09:41:10.810+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_bronze_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T09:41:10.819+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_bronze_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T09:41:10.820+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T09:41:10.820+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 6
[2023-12-30T09:41:10.820+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T09:41:10.831+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): run_dbt_bronze_models> on 2022-09-10 00:00:00+00:00
[2023-12-30T09:41:10.835+0000] {standard_task_runner.py:55} INFO - Started process 1983 to run task
[2023-12-30T09:41:10.837+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_model', 'run_dbt_bronze_models', 'scheduled__2022-09-10T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt._models.py', '--cfg-path', '/tmp/tmpmoevjvh7']
[2023-12-30T09:41:10.837+0000] {standard_task_runner.py:83} INFO - Job 112: Subtask run_dbt_bronze_models
[2023-12-30T09:41:10.882+0000] {task_command.py:376} INFO - Running <TaskInstance: dbt_model.run_dbt_bronze_models scheduled__2022-09-10T00:00:00+00:00 [running]> on host 683423f116e7
[2023-12-30T09:41:10.933+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alonso_md
AIRFLOW_CTX_DAG_ID=dbt_model
AIRFLOW_CTX_TASK_ID=run_dbt_bronze_models
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T00:00:00+00:00
[2023-12-30T09:41:10.934+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-12-30T09:41:10.935+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "    dbt run     --profiles-dir //opt/***/dags/../dbt/     --project-dir ///opt/***/dags/../dbt//dwh     --target prod_*** --vars '{ target_date: 2022-09-10 }' --select bronze"]
[2023-12-30T09:41:10.944+0000] {subprocess.py:86} INFO - Output:
[2023-12-30T09:41:13.057+0000] {subprocess.py:93} INFO - [0m09:41:13  Running with dbt=1.4.6
[2023-12-30T09:41:13.213+0000] {subprocess.py:93} INFO - [0m09:41:13  Found 8 models, 15 tests, 0 snapshots, 0 analyses, 703 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2023-12-30T09:41:13.215+0000] {subprocess.py:93} INFO - [0m09:41:13
[2023-12-30T09:41:13.316+0000] {subprocess.py:93} INFO - [0m09:41:13  Concurrency: 4 threads (target='prod_***')
[2023-12-30T09:41:13.316+0000] {subprocess.py:93} INFO - [0m09:41:13
[2023-12-30T09:41:13.325+0000] {subprocess.py:93} INFO - [0m09:41:13  1 of 3 START sql view model bronze.raw_daily_customer_cdc ...................... [RUN]
[2023-12-30T09:41:13.326+0000] {subprocess.py:93} INFO - [0m09:41:13  2 of 3 START sql view model bronze.raw_daily_customer_drivers .................. [RUN]
[2023-12-30T09:41:13.328+0000] {subprocess.py:93} INFO - [0m09:41:13  3 of 3 START sql view model bronze.raw_daily_loan_transactions ................. [RUN]
[2023-12-30T09:41:13.423+0000] {subprocess.py:93} INFO - [0m09:41:13  1 of 3 ERROR creating sql view model bronze.raw_daily_customer_cdc ............. [[31mERROR[0m in 0.09s]
[2023-12-30T09:41:13.426+0000] {subprocess.py:93} INFO - [0m09:41:13  3 of 3 ERROR creating sql view model bronze.raw_daily_loan_transactions ........ [[31mERROR[0m in 0.09s]
[2023-12-30T09:41:13.428+0000] {subprocess.py:93} INFO - [0m09:41:13  2 of 3 ERROR creating sql view model bronze.raw_daily_customer_drivers ......... [[31mERROR[0m in 0.10s]
[2023-12-30T09:41:13.542+0000] {subprocess.py:93} INFO - [0m09:41:13
[2023-12-30T09:41:13.543+0000] {subprocess.py:93} INFO - [0m09:41:13  Finished running 3 view models in 0 hours 0 minutes and 0.33 seconds (0.33s).
[2023-12-30T09:41:13.555+0000] {subprocess.py:93} INFO - [0m09:41:13
[2023-12-30T09:41:13.555+0000] {subprocess.py:93} INFO - [0m09:41:13  [31mCompleted with 3 errors and 0 warnings:[0m
[2023-12-30T09:41:13.556+0000] {subprocess.py:93} INFO - [0m09:41:13
[2023-12-30T09:41:13.556+0000] {subprocess.py:93} INFO - [0m09:41:13  [33mDatabase Error in model raw_daily_customer_cdc (models/bronze/raw_daily_customer_cdc.sql)[0m
[2023-12-30T09:41:13.556+0000] {subprocess.py:93} INFO - [0m09:41:13    relation "airbyte.daily_customer_information_cdc" does not exist
[2023-12-30T09:41:13.556+0000] {subprocess.py:93} INFO - [0m09:41:13    LINE 9:     FROM "dwh"."airbyte"."daily_customer_information_cdc"
[2023-12-30T09:41:13.557+0000] {subprocess.py:93} INFO - [0m09:41:13                     ^
[2023-12-30T09:41:13.557+0000] {subprocess.py:93} INFO - [0m09:41:13    compiled Code at target/run/dwh/models/bronze/raw_daily_customer_cdc.sql
[2023-12-30T09:41:13.557+0000] {subprocess.py:93} INFO - [0m09:41:13
[2023-12-30T09:41:13.557+0000] {subprocess.py:93} INFO - [0m09:41:13  [33mDatabase Error in model raw_daily_loan_transactions (models/bronze/raw_daily_loan_transactions.sql)[0m
[2023-12-30T09:41:13.558+0000] {subprocess.py:93} INFO - [0m09:41:13    relation "airbyte.daily_loan_transactions" does not exist
[2023-12-30T09:41:13.558+0000] {subprocess.py:93} INFO - [0m09:41:13    LINE 9:     FROM "dwh"."airbyte"."daily_loan_transactions"
[2023-12-30T09:41:13.558+0000] {subprocess.py:93} INFO - [0m09:41:13                     ^
[2023-12-30T09:41:13.559+0000] {subprocess.py:93} INFO - [0m09:41:13    compiled Code at target/run/dwh/models/bronze/raw_daily_loan_transactions.sql
[2023-12-30T09:41:13.559+0000] {subprocess.py:93} INFO - [0m09:41:13
[2023-12-30T09:41:13.559+0000] {subprocess.py:93} INFO - [0m09:41:13  [33mDatabase Error in model raw_daily_customer_drivers (models/bronze/raw_daily_customer_drivers.sql)[0m
[2023-12-30T09:41:13.559+0000] {subprocess.py:93} INFO - [0m09:41:13    relation "airbyte.daily_customer_drivers" does not exist
[2023-12-30T09:41:13.560+0000] {subprocess.py:93} INFO - [0m09:41:13    LINE 9:     FROM "dwh"."airbyte"."daily_customer_drivers"
[2023-12-30T09:41:13.560+0000] {subprocess.py:93} INFO - [0m09:41:13                     ^
[2023-12-30T09:41:13.560+0000] {subprocess.py:93} INFO - [0m09:41:13    compiled Code at target/run/dwh/models/bronze/raw_daily_customer_drivers.sql
[2023-12-30T09:41:13.560+0000] {subprocess.py:93} INFO - [0m09:41:13
[2023-12-30T09:41:13.561+0000] {subprocess.py:93} INFO - [0m09:41:13  Done. PASS=0 WARN=0 ERROR=3 SKIP=0 TOTAL=3
[2023-12-30T09:41:14.494+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-30T09:41:14.503+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-30T09:41:14.506+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_model, task_id=run_dbt_bronze_models, execution_date=20220910T000000, start_date=20231230T094110, end_date=20231230T094114
[2023-12-30T09:41:14.524+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 112 for task run_dbt_bronze_models (Bash command failed. The command returned a non-zero exit code 1.; 1983)
[2023-12-30T09:41:14.545+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-30T09:41:14.573+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-30T10:16:31.587+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_bronze_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T10:16:31.596+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dbt_model.run_dbt_bronze_models scheduled__2022-09-10T00:00:00+00:00 [queued]>
[2023-12-30T10:16:31.596+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T10:16:31.596+0000] {taskinstance.py:1363} INFO - Starting attempt 4 of 6
[2023-12-30T10:16:31.596+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-12-30T10:16:31.607+0000] {taskinstance.py:1383} INFO - Executing <Task(BashOperator): run_dbt_bronze_models> on 2022-09-10 00:00:00+00:00
[2023-12-30T10:16:31.610+0000] {standard_task_runner.py:55} INFO - Started process 3776 to run task
[2023-12-30T10:16:31.613+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dbt_model', 'run_dbt_bronze_models', 'scheduled__2022-09-10T00:00:00+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/run_dbt._models.py', '--cfg-path', '/tmp/tmp1ztyy7g5']
[2023-12-30T10:16:31.613+0000] {standard_task_runner.py:83} INFO - Job 116: Subtask run_dbt_bronze_models
[2023-12-30T10:16:31.655+0000] {task_command.py:376} INFO - Running <TaskInstance: dbt_model.run_dbt_bronze_models scheduled__2022-09-10T00:00:00+00:00 [running]> on host 683423f116e7
[2023-12-30T10:16:31.704+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=alonso_md
AIRFLOW_CTX_DAG_ID=dbt_model
AIRFLOW_CTX_TASK_ID=run_dbt_bronze_models
AIRFLOW_CTX_EXECUTION_DATE=2022-09-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-10T00:00:00+00:00
[2023-12-30T10:16:31.705+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-12-30T10:16:31.706+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "    dbt run     --profiles-dir //opt/***/dags/../dbt/     --project-dir ///opt/***/dags/../dbt//dwh     --target prod_*** --vars '{ target_date: 2022-09-10 }' --select bronze"]
[2023-12-30T10:16:31.714+0000] {subprocess.py:86} INFO - Output:
[2023-12-30T10:16:33.281+0000] {subprocess.py:93} INFO - [0m10:16:33  Running with dbt=1.4.6
[2023-12-30T10:16:33.369+0000] {subprocess.py:93} INFO - [0m10:16:33  Found 8 models, 15 tests, 0 snapshots, 0 analyses, 703 macros, 0 operations, 0 seed files, 3 sources, 0 exposures, 0 metrics
[2023-12-30T10:16:33.371+0000] {subprocess.py:93} INFO - [0m10:16:33
[2023-12-30T10:16:33.433+0000] {subprocess.py:93} INFO - [0m10:16:33  Concurrency: 4 threads (target='prod_***')
[2023-12-30T10:16:33.433+0000] {subprocess.py:93} INFO - [0m10:16:33
[2023-12-30T10:16:33.439+0000] {subprocess.py:93} INFO - [0m10:16:33  1 of 3 START sql view model bronze.raw_daily_customer_cdc ...................... [RUN]
[2023-12-30T10:16:33.440+0000] {subprocess.py:93} INFO - [0m10:16:33  2 of 3 START sql view model bronze.raw_daily_customer_drivers .................. [RUN]
[2023-12-30T10:16:33.441+0000] {subprocess.py:93} INFO - [0m10:16:33  3 of 3 START sql view model bronze.raw_daily_loan_transactions ................. [RUN]
[2023-12-30T10:16:33.506+0000] {subprocess.py:93} INFO - [0m10:16:33  3 of 3 ERROR creating sql view model bronze.raw_daily_loan_transactions ........ [[31mERROR[0m in 0.06s]
[2023-12-30T10:16:33.510+0000] {subprocess.py:93} INFO - [0m10:16:33  2 of 3 ERROR creating sql view model bronze.raw_daily_customer_drivers ......... [[31mERROR[0m in 0.07s]
[2023-12-30T10:16:33.511+0000] {subprocess.py:93} INFO - [0m10:16:33  1 of 3 ERROR creating sql view model bronze.raw_daily_customer_cdc ............. [[31mERROR[0m in 0.07s]
[2023-12-30T10:16:33.548+0000] {subprocess.py:93} INFO - [0m10:16:33
[2023-12-30T10:16:33.548+0000] {subprocess.py:93} INFO - [0m10:16:33  Finished running 3 view models in 0 hours 0 minutes and 0.18 seconds (0.18s).
[2023-12-30T10:16:33.558+0000] {subprocess.py:93} INFO - [0m10:16:33
[2023-12-30T10:16:33.559+0000] {subprocess.py:93} INFO - [0m10:16:33  [31mCompleted with 3 errors and 0 warnings:[0m
[2023-12-30T10:16:33.559+0000] {subprocess.py:93} INFO - [0m10:16:33
[2023-12-30T10:16:33.560+0000] {subprocess.py:93} INFO - [0m10:16:33  [33mDatabase Error in model raw_daily_loan_transactions (models/bronze/raw_daily_loan_transactions.sql)[0m
[2023-12-30T10:16:33.560+0000] {subprocess.py:93} INFO - [0m10:16:33    column "date" does not exist
[2023-12-30T10:16:33.560+0000] {subprocess.py:93} INFO - [0m10:16:33    LINE 12:     cast(date as date) as date,
[2023-12-30T10:16:33.561+0000] {subprocess.py:93} INFO - [0m10:16:33                      ^
[2023-12-30T10:16:33.561+0000] {subprocess.py:93} INFO - [0m10:16:33    HINT:  Perhaps you meant to reference the column "raw_daily_loan_transactions.﻿date".
[2023-12-30T10:16:33.561+0000] {subprocess.py:93} INFO - [0m10:16:33    compiled Code at target/run/dwh/models/bronze/raw_daily_loan_transactions.sql
[2023-12-30T10:16:33.561+0000] {subprocess.py:93} INFO - [0m10:16:33
[2023-12-30T10:16:33.562+0000] {subprocess.py:93} INFO - [0m10:16:33  [33mDatabase Error in model raw_daily_customer_drivers (models/bronze/raw_daily_customer_drivers.sql)[0m
[2023-12-30T10:16:33.562+0000] {subprocess.py:93} INFO - [0m10:16:33    column "date" does not exist
[2023-12-30T10:16:33.562+0000] {subprocess.py:93} INFO - [0m10:16:33    LINE 12:     cast(date as date) as date,
[2023-12-30T10:16:33.563+0000] {subprocess.py:93} INFO - [0m10:16:33                      ^
[2023-12-30T10:16:33.563+0000] {subprocess.py:93} INFO - [0m10:16:33    HINT:  Perhaps you meant to reference the column "raw_daily_customer_drivers.﻿date".
[2023-12-30T10:16:33.563+0000] {subprocess.py:93} INFO - [0m10:16:33    compiled Code at target/run/dwh/models/bronze/raw_daily_customer_drivers.sql
[2023-12-30T10:16:33.563+0000] {subprocess.py:93} INFO - [0m10:16:33
[2023-12-30T10:16:33.564+0000] {subprocess.py:93} INFO - [0m10:16:33  [33mDatabase Error in model raw_daily_customer_cdc (models/bronze/raw_daily_customer_cdc.sql)[0m
[2023-12-30T10:16:33.564+0000] {subprocess.py:93} INFO - [0m10:16:33    column "date" does not exist
[2023-12-30T10:16:33.564+0000] {subprocess.py:93} INFO - [0m10:16:33    LINE 12:     cast(date as date) as date,
[2023-12-30T10:16:33.564+0000] {subprocess.py:93} INFO - [0m10:16:33                      ^
[2023-12-30T10:16:33.565+0000] {subprocess.py:93} INFO - [0m10:16:33    HINT:  Perhaps you meant to reference the column "raw_daily_customer_cdc.﻿date".
[2023-12-30T10:16:33.565+0000] {subprocess.py:93} INFO - [0m10:16:33    compiled Code at target/run/dwh/models/bronze/raw_daily_customer_cdc.sql
[2023-12-30T10:16:33.565+0000] {subprocess.py:93} INFO - [0m10:16:33
[2023-12-30T10:16:33.565+0000] {subprocess.py:93} INFO - [0m10:16:33  Done. PASS=0 WARN=0 ERROR=3 SKIP=0 TOTAL=3
[2023-12-30T10:16:34.520+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-30T10:16:34.528+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-30T10:16:34.530+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_model, task_id=run_dbt_bronze_models, execution_date=20220910T000000, start_date=20231230T101631, end_date=20231230T101634
[2023-12-30T10:16:34.542+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 116 for task run_dbt_bronze_models (Bash command failed. The command returned a non-zero exit code 1.; 3776)
[2023-12-30T10:16:34.555+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-12-30T10:16:34.581+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
